export { LoginPage } from './auth/LoginPage'
export { RegisterPage } from './auth/RegisterPage'
export { DashboardPage } from './dashboard/DashboardPage'
export { default as ExamplePage } from './example/ExamplePage'
export { default as UserProfilePage } from './userProfile/UserProfilePage'
export { ActivitiesPage } from './activities/ActivitiesPage'
export { ActivityDetailsPage } from './activities/ActivityDetailsPage'
export { TaskListsPage } from './taskLists/TaskListsPage'
