/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/activities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obtiene todas las actividades del usuario autenticado. */
    get: {
      parameters: {
        query?: {
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityResponsePaginatedResponse']
            'application/json': components['schemas']['ActivityResponsePaginatedResponse']
            'text/json': components['schemas']['ActivityResponsePaginatedResponse']
          }
        }
      }
    }
    put?: never
    /** Crea una nueva actividad para el usuario autenticado. */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Nombre, categoría y opciones. */
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateActivityCommand']
          'text/json': components['schemas']['CreateActivityCommand']
          'application/*+json': components['schemas']['CreateActivityCommand']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityResponse']
            'application/json': components['schemas']['ActivityResponse']
            'text/json': components['schemas']['ActivityResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activities/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obtiene una actividad específica por su ID. */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description ID de la actividad. */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityResponse']
            'application/json': components['schemas']['ActivityResponse']
            'text/json': components['schemas']['ActivityResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    /** Actualiza una actividad (solo dueño). */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description ID de la actividad. */
          id: string
        }
        cookie?: never
      }
      /** @description Nuevos datos. */
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateActivityCommand']
          'text/json': components['schemas']['UpdateActivityCommand']
          'application/*+json': components['schemas']['UpdateActivityCommand']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityResponse']
            'application/json': components['schemas']['ActivityResponse']
            'text/json': components['schemas']['ActivityResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    /** Elimina una actividad (solo dueño). */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description ID de la actividad. */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activity-logs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Lista los registros de actividad con filtros opcionales. */
    get: {
      parameters: {
        query?: {
          activityId?: string
          from?: string
          to?: string
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityLogResponsePaginatedResponse']
            'application/json': components['schemas']['ActivityLogResponsePaginatedResponse']
            'text/json': components['schemas']['ActivityLogResponsePaginatedResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activity-logs/active': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Lista los registros de actividad que están en curso. */
    get: {
      parameters: {
        query?: {
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityLogResponsePaginatedResponse']
            'application/json': components['schemas']['ActivityLogResponsePaginatedResponse']
            'text/json': components['schemas']['ActivityLogResponsePaginatedResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activity-logs/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obtiene un registro de actividad por ID. */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityLogResponse']
            'application/json': components['schemas']['ActivityLogResponse']
            'text/json': components['schemas']['ActivityLogResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    /** Actualiza un registro de actividad. */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateActivityLogCommand']
          'text/json': components['schemas']['UpdateActivityLogCommand']
          'application/*+json': components['schemas']['UpdateActivityLogCommand']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityLogResponse']
            'application/json': components['schemas']['ActivityLogResponse']
            'text/json': components['schemas']['ActivityLogResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activity-logs/start': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Inicia un registro de actividad (crea un nuevo log). */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['StartActivityCommand']
          'text/json': components['schemas']['StartActivityCommand']
          'application/*+json': components['schemas']['StartActivityCommand']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityLogResponse']
            'application/json': components['schemas']['ActivityLogResponse']
            'text/json': components['schemas']['ActivityLogResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activity-logs/{id}/stop': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Detiene un registro de actividad en curso. */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityLogResponse']
            'application/json': components['schemas']['ActivityLogResponse']
            'text/json': components['schemas']['ActivityLogResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activity-logs/{id}/values': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obtiene los valores personalizados de un registro de actividad. */
    get: {
      parameters: {
        query?: {
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['LogValueResponsePaginatedResponse']
            'application/json': components['schemas']['LogValueResponsePaginatedResponse']
            'text/json': components['schemas']['LogValueResponsePaginatedResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    /** Guarda los valores personalizados para un registro de actividad. */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['SaveLogValuesCommand']
          'text/json': components['schemas']['SaveLogValuesCommand']
          'application/*+json': components['schemas']['SaveLogValuesCommand']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['LogValueResponse'][]
            'application/json': components['schemas']['LogValueResponse'][]
            'text/json': components['schemas']['LogValueResponse'][]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activities/{activityId}/definitions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Lista las definiciones de valores de una actividad. */
    get: {
      parameters: {
        query?: {
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path: {
          activityId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityValueDefinitionResponsePaginatedResponse']
            'application/json': components['schemas']['ActivityValueDefinitionResponsePaginatedResponse']
            'text/json': components['schemas']['ActivityValueDefinitionResponsePaginatedResponse']
          }
        }
      }
    }
    put?: never
    /** Crea una definición de valor para la actividad. */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          activityId: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateValueDefinitionCommand']
          'text/json': components['schemas']['CreateValueDefinitionCommand']
          'application/*+json': components['schemas']['CreateValueDefinitionCommand']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityValueDefinitionResponse']
            'application/json': components['schemas']['ActivityValueDefinitionResponse']
            'text/json': components['schemas']['ActivityValueDefinitionResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activities/{activityId}/definitions/{definitionId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obtiene una definición de valor por ID. */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          activityId: string
          definitionId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityValueDefinitionResponse']
            'application/json': components['schemas']['ActivityValueDefinitionResponse']
            'text/json': components['schemas']['ActivityValueDefinitionResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    /** Actualiza una definición de valor. */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          activityId: string
          definitionId: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateValueDefinitionCommand']
          'text/json': components['schemas']['UpdateValueDefinitionCommand']
          'application/*+json': components['schemas']['UpdateValueDefinitionCommand']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityValueDefinitionResponse']
            'application/json': components['schemas']['ActivityValueDefinitionResponse']
            'text/json': components['schemas']['ActivityValueDefinitionResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    /** Elimina una definición de valor. */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          activityId: string
          definitionId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Registra un nuevo usuario en el sistema. */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['RegisterCommand']
          'text/json': components['schemas']['RegisterCommand']
          'application/*+json': components['schemas']['RegisterCommand']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['UserResponse']
            'application/json': components['schemas']['UserResponse']
            'text/json': components['schemas']['UserResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Inicia sesión y devuelve access token y refresh token. */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['LoginCommand']
          'text/json': components['schemas']['LoginCommand']
          'application/*+json': components['schemas']['LoginCommand']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TokenResponse']
            'application/json': components['schemas']['TokenResponse']
            'text/json': components['schemas']['TokenResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Renueva el access token usando un refresh token válido. */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['SubmitRefreshToken']
          'text/json': components['schemas']['SubmitRefreshToken']
          'application/*+json': components['schemas']['SubmitRefreshToken']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TokenResponse']
            'application/json': components['schemas']['TokenResponse']
            'text/json': components['schemas']['TokenResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obtiene todas las categorías del usuario autenticado. */
    get: {
      parameters: {
        query?: {
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['CategoryResponsePaginatedResponse']
            'application/json': components['schemas']['CategoryResponsePaginatedResponse']
            'text/json': components['schemas']['CategoryResponsePaginatedResponse']
          }
        }
      }
    }
    put?: never
    /** Crea una nueva categoría para el usuario autenticado. */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Nombre de la categoría. */
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateCategoryCommand']
          'text/json': components['schemas']['CreateCategoryCommand']
          'application/*+json': components['schemas']['CreateCategoryCommand']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['CategoryResponse']
            'application/json': components['schemas']['CategoryResponse']
            'text/json': components['schemas']['CategoryResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obtiene una categoría específica por ID. */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description ID de la categoría. */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['CategoryResponse']
            'application/json': components['schemas']['CategoryResponse']
            'text/json': components['schemas']['CategoryResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    /** Actualiza una categoría (solo dueño). */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description ID de la categoría. */
          id: string
        }
        cookie?: never
      }
      /** @description Nuevos datos. */
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateCategoryCommand']
          'text/json': components['schemas']['UpdateCategoryCommand']
          'application/*+json': components['schemas']['UpdateCategoryCommand']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['CategoryResponse']
            'application/json': components['schemas']['CategoryResponse']
            'text/json': components['schemas']['CategoryResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    /** Elimina una categoría (solo dueño). */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description ID de la categoría. */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Devuelve el estado general del servicio sin detalles. */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Servicio saludable. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['HealthStatusResponse']
            'application/json': components['schemas']['HealthStatusResponse']
            'text/json': components['schemas']['HealthStatusResponse']
          }
        }
        /** @description Servicio degradado o no saludable. */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['HealthStatusResponse']
            'application/json': components['schemas']['HealthStatusResponse']
            'text/json': components['schemas']['HealthStatusResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health/details': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Devuelve un reporte detallado del estado de salud de los componentes del sistema. */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Todos los componentes están saludables. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['HealthDetailsResponse']
            'application/json': components['schemas']['HealthDetailsResponse']
            'text/json': components['schemas']['HealthDetailsResponse']
          }
        }
        /** @description Al menos un componente crítico falló. */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['HealthDetailsResponse']
            'application/json': components['schemas']['HealthDetailsResponse']
            'text/json': components['schemas']['HealthDetailsResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/reports/activities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Genera un reporte detallado de registros de actividades con anidamiento completo (Categorías, Valores, etc). */
    get: {
      parameters: {
        query?: {
          StartDate?: string
          EndDate?: string
          CategoryIds?: string[]
          ActivityIds?: string[]
          MinDurationMinutes?: number
          SearchTerm?: string
          OnlyCompleted?: boolean
          UserId?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ActivityReportResponse']
            'application/json': components['schemas']['ActivityReportResponse']
            'text/json': components['schemas']['ActivityReportResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/roles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Lista todos los roles. */
    get: {
      parameters: {
        query?: {
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['RoleResponsePaginatedResponse']
            'application/json': components['schemas']['RoleResponsePaginatedResponse']
            'text/json': components['schemas']['RoleResponsePaginatedResponse']
          }
        }
      }
    }
    put?: never
    /** Crea un nuevo rol. */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateRoleCommand']
          'text/json': components['schemas']['CreateRoleCommand']
          'application/*+json': components['schemas']['CreateRoleCommand']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['RoleResponse']
            'application/json': components['schemas']['RoleResponse']
            'text/json': components['schemas']['RoleResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/roles/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obtiene un rol por su ID. */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['RoleResponse']
            'application/json': components['schemas']['RoleResponse']
            'text/json': components['schemas']['RoleResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    /** Elimina un rol por ID. */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/task-lists': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TaskListResponsePaginatedResponse']
            'application/json': components['schemas']['TaskListResponsePaginatedResponse']
            'text/json': components['schemas']['TaskListResponsePaginatedResponse']
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateTaskListCommand']
          'text/json': components['schemas']['CreateTaskListCommand']
          'application/*+json': components['schemas']['CreateTaskListCommand']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TaskListResponse']
            'application/json': components['schemas']['TaskListResponse']
            'text/json': components['schemas']['TaskListResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/task-lists/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TaskListResponse']
            'application/json': components['schemas']['TaskListResponse']
            'text/json': components['schemas']['TaskListResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateTaskListCommand']
          'text/json': components['schemas']['UpdateTaskListCommand']
          'application/*+json': components['schemas']['UpdateTaskListCommand']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TaskListResponse']
            'application/json': components['schemas']['TaskListResponse']
            'text/json': components['schemas']['TaskListResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tasks/by-task-list/{taskListId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path: {
          taskListId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TaskResponsePaginatedResponse']
            'application/json': components['schemas']['TaskResponsePaginatedResponse']
            'text/json': components['schemas']['TaskResponsePaginatedResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tasks/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TaskResponse']
            'application/json': components['schemas']['TaskResponse']
            'text/json': components['schemas']['TaskResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateTaskCommand']
          'text/json': components['schemas']['UpdateTaskCommand']
          'application/*+json': components['schemas']['UpdateTaskCommand']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TaskResponse']
            'application/json': components['schemas']['TaskResponse']
            'text/json': components['schemas']['TaskResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tasks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateTaskCommand']
          'text/json': components['schemas']['CreateTaskCommand']
          'application/*+json': components['schemas']['CreateTaskCommand']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TaskResponse']
            'application/json': components['schemas']['TaskResponse']
            'text/json': components['schemas']['TaskResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tasks/{id}/toggle': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    trace?: never
  }
  '/api/v1/users/{userId}/roles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obtiene los roles asignados a un usuario. */
    get: {
      parameters: {
        query?: {
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path: {
          userId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['RoleResponsePaginatedResponse']
            'application/json': components['schemas']['RoleResponsePaginatedResponse']
            'text/json': components['schemas']['RoleResponsePaginatedResponse']
          }
        }
      }
    }
    /** Reemplaza todos los roles del usuario por la lista indicada (por nombre). */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          userId: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['SetUserRolesCommand']
          'text/json': components['schemas']['SetUserRolesCommand']
          'application/*+json': components['schemas']['SetUserRolesCommand']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{userId}/roles/{roleId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Asigna un rol a un usuario. */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          userId: string
          roleId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    /** Quita un rol de un usuario. */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          userId: string
          roleId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obtiene los datos del usuario autenticado (autogestión). */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['UserResponse']
            'application/json': components['schemas']['UserResponse']
            'text/json': components['schemas']['UserResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    /** Actualiza los datos del usuario autenticado (autogestión). */
    put: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateUserCommand']
          'text/json': components['schemas']['UpdateUserCommand']
          'application/*+json': components['schemas']['UpdateUserCommand']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['UserResponse']
            'application/json': components['schemas']['UserResponse']
            'text/json': components['schemas']['UserResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Lista todos los usuarios (solo Admin). */
    get: {
      parameters: {
        query?: {
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['UserResponsePaginatedResponse']
            'application/json': components['schemas']['UserResponsePaginatedResponse']
            'text/json': components['schemas']['UserResponsePaginatedResponse']
          }
        }
      }
    }
    put?: never
    /** Crea un nuevo usuario (solo Admin). */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateUserCommand']
          'text/json': components['schemas']['CreateUserCommand']
          'application/*+json': components['schemas']['CreateUserCommand']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['UserResponse']
            'application/json': components['schemas']['UserResponse']
            'text/json': components['schemas']['UserResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obtiene un usuario por su ID (solo Admin). */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['UserResponse']
            'application/json': components['schemas']['UserResponse']
            'text/json': components['schemas']['UserResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    /** Actualiza un usuario por ID (solo Admin). */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateUserCommand']
          'text/json': components['schemas']['UpdateUserCommand']
          'application/*+json': components['schemas']['UpdateUserCommand']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['UserResponse']
            'application/json': components['schemas']['UserResponse']
            'text/json': components['schemas']['UserResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    /** Elimina un usuario por ID (solo Admin). */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sessions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          pageNumber?: number
          pageSize?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['UserSessionResponsePaginatedResponse']
            'application/json': components['schemas']['UserSessionResponsePaginatedResponse']
            'text/json': components['schemas']['UserSessionResponsePaginatedResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sessions/{sessionId}/revoke': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          sessionId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sessions/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ActivityInfoResponse: {
      /** Format: uuid */
      id?: string
      name?: string | null
      color?: string | null
    }
    ActivityLogDetailResponse: {
      /** Format: uuid */
      logId?: string
      /** Format: date-time */
      startedAt?: string
      /** Format: date-time */
      endedAt?: string | null
      /** Format: double */
      durationMinutes?: number
      activity?: components['schemas']['ActivityInfoResponse']
      category?: components['schemas']['CategoryInfoResponse']
      values?: components['schemas']['LogValueInfoResponse'][] | null
    }
    ActivityLogResponse: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      activityId?: string
      /** Format: date-time */
      startedAt?: string
      /** Format: date-time */
      endedAt?: string | null
    }
    ActivityLogResponsePaginatedResponse: {
      items?: components['schemas']['ActivityLogResponse'][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
    }
    ActivityReportResponse: {
      /** Format: uuid */
      userId?: string
      /** Format: date-time */
      startDate?: string
      /** Format: date-time */
      endDate?: string
      /** Format: double */
      totalDurationMinutes?: number
      logs?: components['schemas']['ActivityLogDetailResponse'][] | null
    }
    ActivityResponse: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      userId?: string
      /** Format: uuid */
      categoryId?: string
      name?: string | null
      color?: string | null
      allowOverlap?: boolean
    }
    ActivityResponsePaginatedResponse: {
      items?: components['schemas']['ActivityResponse'][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
    }
    ActivityValueDefinitionResponse: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      activityId?: string
      name?: string | null
      valueType?: string | null
      isRequired?: boolean
      unit?: string | null
      minValue?: string | null
      maxValue?: string | null
    }
    ActivityValueDefinitionResponsePaginatedResponse: {
      items?: components['schemas']['ActivityValueDefinitionResponse'][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
    }
    CategoryInfoResponse: {
      /** Format: uuid */
      id?: string
      name?: string | null
      color?: string | null
    }
    CategoryResponse: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      userId?: string
      name?: string | null
      description?: string | null
      color?: string | null
    }
    CategoryResponsePaginatedResponse: {
      items?: components['schemas']['CategoryResponse'][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
    }
    CreateActivityCommand: {
      /** Format: uuid */
      categoryId?: string
      name?: string | null
      color?: string | null
      allowOverlap?: boolean
      /** Format: uuid */
      userId?: string
    }
    CreateCategoryCommand: {
      name?: string | null
      description?: string | null
      color?: string | null
      /** Format: uuid */
      userId?: string
    }
    CreateRoleCommand: {
      name?: string | null
    }
    CreateTaskCommand: {
      /** Format: uuid */
      taskListId?: string
      content?: string | null
      /** Format: date-time */
      dueDate?: string | null
      /** Format: uuid */
      userId?: string
    }
    CreateTaskListCommand: {
      name?: string | null
      color?: string | null
      /** Format: uuid */
      userId?: string
    }
    CreateUserCommand: {
      name?: string | null
      email?: string | null
      password?: string | null
    }
    CreateValueDefinitionCommand: {
      /** Format: uuid */
      activityId?: string
      name?: string | null
      valueType?: string | null
      isRequired?: boolean
      unit?: string | null
      minValue?: string | null
      maxValue?: string | null
      /** Format: uuid */
      userId?: string
    }
    HealthDetailsResponse: {
      status?: string | null
      /** Format: double */
      totalDuration?: number
      entries?: components['schemas']['HealthEntryResponse'][] | null
      /** Format: date-time */
      timestamp?: string
    }
    HealthEntryResponse: {
      component?: string | null
      status?: string | null
      description?: string | null
      /** Format: double */
      duration?: number
    }
    HealthStatusResponse: {
      status?: string | null
      /** Format: date-time */
      timestamp?: string
    }
    LogValueInfoResponse: {
      /** Format: uuid */
      definitionId?: string
      name?: string | null
      value?: string | null
      unit?: string | null
      valueType?: string | null
    }
    LogValueItem: {
      /** Format: uuid */
      valueDefinitionId?: string
      value?: string | null
    }
    LogValueResponse: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      activityLogId?: string
      /** Format: uuid */
      valueDefinitionId?: string
      value?: string | null
    }
    LogValueResponsePaginatedResponse: {
      items?: components['schemas']['LogValueResponse'][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
    }
    LoginCommand: {
      email?: string | null
      password?: string | null
      deviceInfo?: string | null
    }
    ProblemDetails: {
      type?: string | null
      title?: string | null
      /** Format: int32 */
      status?: number | null
      detail?: string | null
      instance?: string | null
    } & {
      [key: string]: unknown
    }
    RegisterCommand: {
      name?: string | null
      email?: string | null
      password?: string | null
    }
    RoleResponse: {
      /** Format: uuid */
      id?: string
      name?: string | null
    }
    RoleResponsePaginatedResponse: {
      items?: components['schemas']['RoleResponse'][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
    }
    SaveLogValuesCommand: {
      /** Format: uuid */
      activityLogId?: string
      values?: components['schemas']['LogValueItem'][] | null
      /** Format: uuid */
      userId?: string
    }
    SetUserRolesCommand: {
      /** Format: uuid */
      userId?: string
      roleNames?: string[] | null
    }
    StartActivityCommand: {
      /** Format: uuid */
      activityId?: string
      /** Format: uuid */
      userId?: string
    }
    SubmitRefreshToken: {
      refreshToken?: string | null
    }
    TaskListResponse: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      userId?: string
      name?: string | null
      color?: string | null
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    TaskListResponsePaginatedResponse: {
      items?: components['schemas']['TaskListResponse'][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
    }
    TaskResponse: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      taskListId?: string
      /** Format: uuid */
      userId?: string
      content?: string | null
      isCompleted?: boolean
      /** Format: date-time */
      dueDate?: string | null
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string | null
    }
    TaskResponsePaginatedResponse: {
      items?: components['schemas']['TaskResponse'][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
    }
    TokenResponse: {
      accessToken?: string | null
      refreshToken?: string | null
      /** Format: date-time */
      refreshTokenExpiry?: string
    }
    UpdateActivityCommand: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      categoryId?: string
      name?: string | null
      color?: string | null
      allowOverlap?: boolean
      /** Format: uuid */
      userId?: string
    }
    UpdateActivityLogCommand: {
      /** Format: uuid */
      id?: string
      /** Format: date-time */
      startedAt?: string
      /** Format: date-time */
      endedAt?: string | null
      /** Format: uuid */
      userId?: string
    }
    UpdateCategoryCommand: {
      /** Format: uuid */
      id?: string
      name?: string | null
      description?: string | null
      color?: string | null
      /** Format: uuid */
      userId?: string
    }
    UpdateTaskCommand: {
      /** Format: uuid */
      id?: string
      content?: string | null
      /** Format: date-time */
      dueDate?: string | null
      /** Format: uuid */
      userId?: string
    }
    UpdateTaskListCommand: {
      /** Format: uuid */
      id?: string
      name?: string | null
      color?: string | null
      /** Format: uuid */
      userId?: string
    }
    UpdateUserCommand: {
      /** Format: uuid */
      id?: string
      name?: string | null
      email?: string | null
    }
    UpdateValueDefinitionCommand: {
      /** Format: uuid */
      activityId?: string
      /** Format: uuid */
      definitionId?: string
      name?: string | null
      valueType?: string | null
      isRequired?: boolean
      unit?: string | null
      minValue?: string | null
      maxValue?: string | null
      /** Format: uuid */
      userId?: string
    }
    UserResponse: {
      /** Format: uuid */
      id?: string
      name?: string | null
      email?: string | null
    }
    UserResponsePaginatedResponse: {
      items?: components['schemas']['UserResponse'][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
    }
    UserSessionResponse: {
      /** Format: uuid */
      id?: string
      deviceInfo?: string | null
      ipAddress?: string | null
      location?: string | null
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      expiresAt?: string
      isActive?: boolean
    }
    UserSessionResponsePaginatedResponse: {
      items?: components['schemas']['UserSessionResponse'][] | null
      /** Format: int32 */
      totalCount?: number
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int32 */
      readonly totalPages?: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
